vaadin/osgi

flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OSGiVaadinInitialization.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletContainerInitializerClasses.java
test-containers/felix-jetty/src/test/java/com/vaadin/flow/osgi/CustomContextBaseHrefIT.java

fix: servlet context listener should handle all possible Vaadin contexts

---

flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OSGiResourceProvider.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OSGiVaadinInitialization.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletContainerInitializerClasses.java

fix: rework OSGi lookup and resource provider, make it context based

---

drivers.xml
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OSGiVaadinInitialization.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletContainerInitializerClasses.java

fix: wait for ApplicationConfigurationFactory service in Lookup

---

flow-osgi/bnd.bnd

fix: reduce version requirements for OSGi framework and HTTP context

---

.gitignore
flow-osgi/.gitignore
flow-osgi/bnd.bnd
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/AppConfigFactoryTracker.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OSGiVaadinInitialization.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/servlet/OSGiVaadinServlet.java
test-containers/bnd-tools-smoke-test/app/src/test/java/com/vaadin/flow/osgi/smoketest/SmokeOSGiServletIT.java
test-containers/bnd-tools-smoke-test/test-project/.gitignore
test-containers/bnd-tools-smoke-test/test-project/src/main/java/com/vaadin/flow/smoke/osgi/SmokeOSGiVaadinServlet.java

feat: provide a way to extend OSGi specific servlet to support OSGi

---

flow-osgi/pom.xml
flow-osgi/src/main/feature/feature.xml

feat: add feature classifier

---

flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletContainerInitializerClasses.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/servlet/OSGiVaadinServlet.java

Clean up context when no servlets remaining for the context and use weak references

---

flow-osgi/src/main/java/com/vaadin/flow/osgi/support/AppConfigFactoryTracker.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OSGiVaadinInitialization.java

fix: use cached service references when accessing to Servlets

---

flow-osgi/pom.xml
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OSGiAppShellPredicate.java
flow-osgi/src/test/java/com/vaadin/flow/osgi/support/OSGiAppShellPredicateTest.java

fix: Implement app shell predicate as OSGi service

---

flow-osgi/src/main/java/com/vaadin/flow/osgi/support/AppConfigFactoryTracker.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OSGiStaticFileHandlerFactory.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/OSGiVaadinInitialization.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletInitRequirementsTracker.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletInitializationRequirements.java
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/servlet/OSGiVaadinServlet.java
test-containers/bnd-tools-smoke-test/app/src/test/java/com/vaadin/flow/osgi/smoketest/ServletContextResourceIT.java

fix: implement static file handler factory for OSGi

---

flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletInitRequirementsTracker.java

fix: deregister resource servlet only on web app bundle stop

---

flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletInitRequirementsTracker.java

fix: deregister resource servlet only on web app bundle stop (#59)

---

flow-osgi/bnd.bnd
flow-osgi/pom.xml
flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletInitRequirementsTracker.java

chore: use 7.0 osgi add-on for Flow 7 and 8

---

flow-osgi/src/main/java/com/vaadin/flow/osgi/support/ServletContainerInitializerClasses.java

chore: handle V21 DevModeInitializer package move

---

flow-osgi/pom.xml
test-containers/felix-jetty/pom.xml

Increase flow version compat

---

test-containers/bnd-tools-smoke-test/app/pom.xml
test-containers/felix-jetty/pom.xml
test-containers/karaf/karaf-test-project/pom.xml

fix: add jsr305 to activate JS0N 1.4

---

test-containers/bnd-tools-smoke-test/app/app.bndrun

fix: use flow version set via parameter instead harcoded

---

README.md
flow-osgi/pom.xml
pom.xml
test-containers/bnd-tools-smoke-test/app/pom.xml
test-containers/bnd-tools-smoke-test/pom.xml
test-containers/bnd-tools-smoke-test/test-project/pom.xml
test-containers/felix-jetty/pom.xml
test-containers/karaf/karaf-run/pom.xml
test-containers/karaf/karaf-test-project/pom.xml
test-containers/karaf/pom.xml
test-containers/pom.xml

Update version as the new one requires JDK11

Update version to 8.0-SNAPSHOT

---

test-containers/karaf/karaf-run/pom.xml
test-containers/karaf/pom.xml

Use property to define maven-plugin and karaf distribution version

chore: Define karaf version in one place

---

test-containers/karaf/karaf-run/pom.xml
test-containers/karaf/pom.xml

Pin Karaf version (CP: 7.0)

---

flow-osgi/bnd.bnd
flow-osgi/pom.xml
pom.xml
test-containers/bnd-tools-smoke-test/app/app.bndrun
test-containers/bnd-tools-smoke-test/app/pom.xml

chore: Update license checker version

---

pom.xml

Cherry-pick of #99, #100 and #101

chore: fix incompatibilities between karaf-maven-plugin and maven-deploy-plugin (CP 7.0)

---

pom.xml

Cherry-pick of #99, #100 and #101

chore: fix incompatibilities between karaf-maven-plugin and maven-deploy-plugin (CP 8.0)

---

test-containers/karaf/karaf-run/pom.xml
test-containers/karaf/pom.xml

chore: bump karaf to 4.4.0

---

flow-osgi/pom.xml
test-containers/bnd-tools-smoke-test/app/app.bndrun
test-containers/bnd-tools-smoke-test/app/pom.xml

chore: update license checker 1.7.2

---

flow-osgi/pom.xml
test-containers/bnd-tools-smoke-test/app/app.bndrun
test-containers/bnd-tools-smoke-test/app/pom.xml
test-containers/felix-dependencies-only/pom.xml
test-containers/felix-dependencies-only/src/test/java/com/vaadin/flow/osgi/OSGiDependenciesTest.java
test-containers/pom.xml

Created fast unit test for checking if OSGi dependencies are met before starting long running bnd/felix-jetty/karaf tests.

test: created unit test for checking if OSGi dependencies are met
